export interface IFormInput {
    sendName?: string,
    sendIdPer?: string,
    sendPhone?: number | string,
    sendAddress?: string,
    receiptName?: string,
    receiptIdPer?: string,
    receiptPhone?: number | string,
    receiptAddress?: string,
    packageName?: string,
    packageValue?: string,
    packageWeight?: string,
    packageQuantity?: string,
    shipName?: string,
    price?: number,
    coefficient?: number,
    packagingServicePrice?: number,
    totalPrice?: number,
    sendPay?: number,
    receiptPay?: number,
  }